### ISSUE TITLE
[Issue]: NPE Spam In Console on World load

### ISSUE THREAD

**Issue by Lanse505** [The-Acronym-Coders/O.R.E#2]
https://paste.ee/p/IY07R

**Comment by jaredlll08** [comment]
I need the json file

**Comment by DoughnutDev** [comment]
http://hastebin.com/aqeyabeqoc.json

**Comment by jaredlll08** [comment]
for metadata, use `;` so like `minecraft:coal;1`

and try this version please: http://blamejared.com:8080/job/ORE/11/

**Comment by Lanse505** [comment]
Should I close this?

**Comment by DoughnutDev** [comment]
Yeah
